#!/bin/bash
# GPilot — One-Command Quickstart
# Interactive setup that gets you running in under 5 minutes.
# Usage: bash scripts/quickstart.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"

echo ""
echo "  ╔══════════════════════════════════════╗"
echo "  ║     GPilot — Financial Intelligence  ║"
echo "  ║            Quick Setup               ║"
echo "  ╚══════════════════════════════════════╝"
echo ""

# --- Check prerequisites ---
echo "Checking prerequisites..."

if ! command -v git &>/dev/null; then
  echo "  [x] Git not found. Please install: https://git-scm.com"
  exit 1
fi
echo "  [ok] Git"

if command -v claude &>/dev/null; then
  echo "  [ok] Claude Code"
else
  echo "  [!] Claude Code CLI not detected (will still work if opened via IDE)"
fi

if command -v node &>/dev/null; then
  echo "  [ok] Node.js $(node -v) (for dashboard)"
else
  echo "  [!] Node.js not found (optional — needed only for dashboard)"
fi

echo ""

# --- Interactive configuration ---
echo "Let's configure your workspace."
echo "(Press Enter to accept defaults shown in brackets)"
echo ""

read -rp "  Your name [Your Name]: " input_name
USER_NAME="${input_name:-Your Name}"

# Generate initials from name
default_initials=$(echo "$USER_NAME" | awk '{for(i=1;i<=NF;i++) printf substr($i,1,1)}' | tr '[:lower:]' '[:upper:]')
read -rp "  Your initials [$default_initials]: " input_initials
USER_INITIALS="${input_initials:-$default_initials}"

read -rp "  Organization name [Acme Ventures]: " input_org
ORG_NAME="${input_org:-Acme Ventures}"

read -rp "  Focus sectors [Software/SaaS, AI/ML, Fintech, Healthtech, Deeptech]: " input_sectors
FOCUS_SECTORS="${input_sectors:-Software/SaaS, AI/ML, Fintech, Healthtech, Deeptech}"

echo ""
read -rp "  Perplexity API key (get at perplexity.ai/settings/api, or press Enter to skip): " input_pplx
PERPLEXITY_API_KEY="${input_pplx:-}"

echo ""

# --- Write .env ---
cat > "$ROOT/.env" <<ENVEOF
# GPilot — Configuration (generated by quickstart.sh)

USER_NAME="$USER_NAME"
USER_INITIALS="$USER_INITIALS"
ORG_NAME="$ORG_NAME"
FOCUS_SECTORS="$FOCUS_SECTORS"
PERPLEXITY_API_KEY="$PERPLEXITY_API_KEY"

# Optional — Cloud Storage (macOS only)
HUB_PATH="\$HOME/Documents/gpilot"
ONEDRIVE_PATH=""
GDRIVE_PATH=""
GDRIVE_EMAIL=""

# Optional — Feishu
FEISHU_OPEN_ID=""
ENVEOF

echo "  [ok] .env created"

# --- Run customize ---
echo ""
echo "Applying configuration..."
bash "$ROOT/scripts/customize.sh"

# --- Run setup ---
echo ""
echo "Linking global config..."
bash "$ROOT/scripts/setup.sh"

# --- Summary ---
echo ""
echo "  ╔══════════════════════════════════════╗"
echo "  ║          Setup Complete!             ║"
echo "  ╚══════════════════════════════════════╝"
echo ""
echo "  Workspace: $ROOT"
echo "  Operator:  $USER_NAME ($USER_INITIALS)"
echo "  Org:       $ORG_NAME"
echo "  Sectors:   $FOCUS_SECTORS"
if [ -n "$PERPLEXITY_API_KEY" ]; then
  echo "  Perplexity: configured"
else
  echo "  Perplexity: not set (add later in .env)"
fi
echo ""
echo "  ┌─────────────────────────────────────┐"
echo "  │  Next: Open this folder in Claude   │"
echo "  │  Code and try these commands:       │"
echo "  │                                     │"
echo "  │  /query \"AI infrastructure trends\"  │"
echo "  │  /source-deals                      │"
echo "  │  /deal-screen                       │"
echo "  │  /research                          │"
echo "  └─────────────────────────────────────┘"
echo ""
