#!/usr/bin/env bash
#
# Stop hook — fires when Claude finishes responding in a session.
# Logs session metadata to learnings/_daily-log.md for batch reflection.
#
# Design: this hook MUST be fast (<1s) to avoid blocking session exit.
# Heavy lifting (transcript parsing, learning extraction) happens later
# when /reflect or /review-learnings is invoked manually or by schedule.
#
# Cross-platform: relies on POSIX bash + standard utilities. Tested on
# macOS, Linux, and Windows (Git Bash / WSL).

set -euo pipefail

# ---------- Resolve paths ----------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LEARNINGS_DIR="$REPO_ROOT/learnings"
DAILY_LOG="$LEARNINGS_DIR/_daily-log.md"

# Bail out if we're not actually in a GPilot repo (hook may fire from
# unrelated cwd if user runs Claude Code elsewhere).
if [[ ! -d "$LEARNINGS_DIR" ]]; then
  exit 0
fi

# ---------- Read hook input from stdin ----------
# Claude Code sends JSON like:
# { "session_id": "...", "transcript_path": "...", "cwd": "...",
#   "stop_hook_active": false }
INPUT="$(cat || true)"

# Helper: extract a string field from JSON input (avoids jq dependency)
extract_field() {
  local field="$1"
  echo "$INPUT" \
    | grep -oE "\"$field\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" \
    | head -1 \
    | sed -E 's/.*"([^"]*)"$/\1/' \
    || true
}

SESSION_ID="$(extract_field session_id)"
TRANSCRIPT_PATH="$(extract_field transcript_path)"
CWD="$(extract_field cwd)"
STOP_HOOK_ACTIVE="$(echo "$INPUT" | grep -oE '"stop_hook_active"[[:space:]]*:[[:space:]]*(true|false)' | head -1 | grep -oE '(true|false)' || echo false)"

# Avoid infinite loops: if Claude is already running because of a hook
# stop, don't log it.
if [[ "$STOP_HOOK_ACTIVE" == "true" ]]; then
  exit 0
fi

# Defaults if extraction failed
SESSION_ID="${SESSION_ID:-unknown}"
TRANSCRIPT_PATH="${TRANSCRIPT_PATH:-}"
CWD="${CWD:-$REPO_ROOT}"

DATE_UTC="$(date -u +"%Y-%m-%d")"
TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# ---------- Initialize daily log if missing ----------
if [[ ! -f "$DAILY_LOG" ]]; then
  cat > "$DAILY_LOG" <<'HEADER'
# Daily Reflection Log

> Auto-captured by `.claude/settings.json` Stop hook. Each entry = one
> session ended. Entries here are RAW signal — they get processed weekly
> by `/review-learnings`, which extracts reusable insights and rolls them
> up into `learnings/{agent}.md` files. After processing, entries are
> marked `processed: YYYY-MM-DD` and eventually pruned.
>
> **Do not hand-edit this file** — it is regenerated by the hook.

HEADER
fi

# ---------- Append session entry ----------
{
  echo ""
  echo "## $TIMESTAMP — session ${SESSION_ID:0:12}"
  echo "- **date**: $DATE_UTC"
  echo "- **session_id**: \`$SESSION_ID\`"
  echo "- **cwd**: \`$CWD\`"
  if [[ -n "$TRANSCRIPT_PATH" ]]; then
    echo "- **transcript**: \`$TRANSCRIPT_PATH\`"
  fi
  echo "- **status**: pending_reflection"
} >> "$DAILY_LOG"

# Hook must always exit 0 so it never blocks session exit
exit 0
